# Netlify Build Configuration
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: API proxy won't work for external systems accessing Netlify
# Backend needs to be deployed separately for cross-system access

# Environment variables for production - UPDATE THESE WITH YOUR DEPLOYED BACKEND URL
[context.production.environment]
  VITE_API_URL = "https://your-backend-url.herokuapp.com"
  VITE_SOCKET_URL = "https://your-backend-url.herokuapp.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-backend-url.herokuapp.com"
  VITE_SOCKET_URL = "https://your-backend-url.herokuapp.com"
